<!-- Footer Start -->
  <footer class="footer">
    <div class="footer-container">
      <div class="footer-section">
        <h3>Company</h3>
        <a href="#">About Us</a>
        <a href="#">Contact Us</a>
        <a href="#">Our Services</a>
        <a href="#">Privacy Policy</a>
        <a href="#">Terms & Conditions</a>
      </div>
      <div class="footer-section">
        <h3>Quick Links</h3>
        <a href="#">Careers</a>
        <a href="#">Resources</a>
        <a href="#">Support</a>
        <a href="#">Help Center</a>
        <a href="#">Report an Issue</a>
      </div>
      <div class="footer-section">
        <h3>Contact</h3>
        <a href="https://www.google.com/maps/place/Swinburne+University+of+Technology/@-37.8221504,145.0363797,17z/data=!3m1!4b1!4m6!3m5!1s0x6ad642326bae5aaf:0x75e96bbd4988f769!8m2!3d-37.8221504!4d145.0389546!16zL20vMDFrcV9z?entry=ttu&g_ep=EgoyMDI1MDIxMi4wIKXMDSoASAFQAw%3D%3D">John St, Hawthorn VIC 3122, Australia</a>
        <p>+61 3 9214 8444</p>
        <p>swinburne@edu.au</p>
        <div class="social-links">
          <a href="#">Twitter</a>
          <a href="#">Facebook</a>
          <a href="#">YouTube</a>
          <a href="#">LinkedIn</a>
        </div>
      </div>
      <div class="footer-section">
        <h3>Newsletter</h3>
        <p>Leave your email address here for our latest news.</p>
        <form>
          <input type="email" placeholder="Your email">
          <button type="submit">Sign Up</button>
        </form>
        <div class="youtube">
          <a href="https://www.youtube.com/watch?v=FFGm45dXkLY">
            <img src="styles/images/youtube-logo.svg" alt="YouTube Logo">
          </a>
        </div>

      </div>
    </div>
    <div class="footer-bottom">
      <p>&copy; <a href="home.html">Job Landing</a>, All Right Reserved.</p>
      <div class="footer-menu">
        <a href="#">Home</a>
        <a href="#">Cookies</a>
        <a href="#">Help</a>
        <a href="#">FAQs</a>
      </div>
    </div>
  </footer>
  <!-- Footer End -->