<!-- Header Start -->
    <header class="container">
        <div class="container header-content">
          <a href="index.php" class="logo"><h1 class="logo-web">JobsLanding</h1></a>
          <nav class="navbar-container">
            <ul>
              <li><a href="indphp">Home</a></li>
              <li><a href="about.php">About Us</a></li>
              <li><a href="jobs.php">Jobs</a></li>
              <li><a href="apply.php">Apply</a></li>
              <li><a href="enhancements.php">Enhancements</a></li>
              <li><a href="#" class="login-button">Login</a></li>
            </ul>
          </nav>
          <button class="navbar-hamburger">☰</button>
        </div>
      </header>
    <!-- Header End -->