<!-- Header Start -->
    <header class="container">
        <div class="container header-content">
          <a href="index.html" class="logo"><h1 class="logo-web">JobsLanding</h1></a>
          <nav class="navbar-container">
            <ul>
              <li><a href="index.html">Home</a></li>
              <li><a href="about.html">About Us</a></li>
              <li><a href="jobs.html  ">Jobs</a></li>
              <li><a href="apply.html">Apply</a></li>
              <li><a href="enhancements.html">Enhancements</a></li>
              <li><a href="#" class="login-button">Login</a></li>
            </ul>
          </nav>
          <button class="navbar-hamburger">☰</button>
        </div>
      </header>
    <!-- Header End -->